# Generated by Django 2.0rc1 on 2017-12-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
