# Generated by Django 2.0rc1 on 2017-12-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_auto_20171226_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_pdf',
            field=models.FileField(default='', upload_to='pdf/%y/%m/%d'),
        ),
    ]
