# Generated by Django 2.0rc1 on 2018-01-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0003_book_book_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
